version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          key: circleci-sproingk-{{ checksum "pom.xml" }}
      - run: ./mvnw -B dependency:go-offline -Dversions-maven-plugin.phase=none -Dboxfuse.healthcheck.path=/actuator/health -Dboxfuse.env=prod
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sproingk-{{ checksum "pom.xml" }}
      - run: ./mvnw -B clean verify -Dversions-maven-plugin.phase=none -Dboxfuse.healthcheck.path=/actuator/health -Dboxfuse.env=prod
      - store_test_results:
          path: target/{surefire,failsafe}-reports
      - run: ./mvnw -B boxfuse:run -Dversions-maven-plugin.phase=none -Dboxfuse.healthcheck.path=/actuator/health -Dboxfuse.env=prod
      - run: ./health-check.py
