version: 2
jobs:
  build:
    working_directory: ~/sproingk
    docker:
      - image: circleci/openjdk:8

    environment:
      MAVEN_OPTS: "-Dversions-maven-plugin.phase=none -Dboxfuse.healthcheck.path=/application/health -Dboxfuse.env=prod"

    steps:
      - checkout
  
      - restore_cache:
          key: circleci-sproingk-{{ checksum "pom.xml" }}
      - run: ./mvnw -B dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sproingk-{{ checksum "pom.xml" }}

      - run: ./mvnw -B clean verify

      - store_test_results:
          path: target/{surefire,failsafe}-reports

      - run: ./mvnw -B boxfuse:run
      - run: ./health-check.py
